[tools]
git-lfs = { version = "latest" }
lazygit = { version = "latest" }
ghq = { version = "latest" }
"npm:cz-git" = { version = "latest" }
"npm:czg" = { version = "latest" }

# github
github-cli = { version = "latest" }
# gitlab
"gitlab:gitlab-org/cli" = { version = "latest" }
